### PR TITLE
[WIP] Reset tarball timestamps

### PR DESCRIPTION
**Pull request by lslezak**
This is just to discuss the proposed idea for building the same tarballs if the sources are not changed.

### CODE REVIEW

**Comment by lslezak** [comment]
The disadvantage is that the files in the tarball have zero time stamps (01-01-1970), which IMO is not nice in some cases they are useful... :worried:

**Comment by mvidner** [comment]
Interesting. Did I miss a discussion somewhere? 

If the idea is to have reproducible builds, wouldn't it be more appropriate to fix this in the `gem` command?

**Comment by jreidinger** [comment]
@mvidner see yast-devel. Idea is to have same tarballs in IBS and OBS even if send by  different workers.

**Comment by mvidner** [comment]
> see yast-devel

OK, this one: https://lists.opensuse.org/yast-devel/2017-01/msg00032.html with the thread starting at https://lists.opensuse.org/yast-devel/2017-01/msg00004.html

I thought git had to have something similar, and it does:

> [git archive](https://git-scm.com/docs/git-archive) behaves differently when given a tree ID versus when given a commit ID or tag ID. In the first case the current time is used as the modification time of each file in the archive. In the latter case the commit time as recorded in the referenced commit object is used instead.

**Comment by mvidner** [comment]
@lslezak I think this would work better and we could reuse the standard task:

>    The `TAR_OPTIONS` environment variable specifies default options to
be placed in front of any explicit options.  For example, if
`TAR_OPTIONS` is `-v --unlink-first`, `tar` behaves as if the two
options `-v` and `--unlink-first` had been specified before any
explicit options.  Option specifications are separated by whitespace.
A backslash escapes the next character, so it can be used to specify an
option containing whitespace or a backslash.

**Comment by lslezak** [comment]
This has been actually solved in #43 and #44 => closing.

**Pull request closed without merging**
